image: docker:stable
services:
- docker:dind
stages:
- emacs
- publish
- ana
variables:
  CI_REGISTRY_BASE: ${CI_REGISTRY}/${CI_PROJECT_PATH}
before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

img-emacs-latest:
  stage: emacs
  variables:
    CI_REGISTRY_IMAGE: ${CI_REGISTRY_BASE}/emacs-latest
    CI_PATH: emacs-latest
  script:
    - docker build -t $CI_REGISTRY_IMAGE $CI_PATH
    - docker tag $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
  resource_group: group-emacs
