name: Docker image

on: [push]

jobs:

  build-publish:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build the publish Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ody55eus/publish
        dockerfile: publish/Dockerfile
        tags: latest
        
  build-trajectory:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build the trajectory Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ody55eus/trajectory-recognition
        dockerfile: trajectory-recognition/Dockerfile
        tags: latest


  build-evaluate:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build the evaluate Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: evaluate/Dockerfile
        repository: ody55eus/evaluate
        tags: latest

  build-flowers:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: write kagglejson
      run: echo "$KAGGLEJSON" > kaggle.json
      env:
        KAGGLEJSON: ${{ secrets.KAGGLEJSON }}

    - name: Build the flowers Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: flowers/Dockerfile
        repository: ody55eus/flowers
        tags: latest
