name: Emacs-Latest Docker image

on:
  push:
    branches:
      - master

  schedule:
    # build every week
    - cron: "0 0 */7 * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build-emacs-latest:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build the emacs-latest Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ody55eus/emacs-latest
        dockerfile: emacs-latest/Dockerfile
        tags: latest

  build-ana:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build the ana Docker image
      uses: docker/build-push-action@v1
      env:
        SSH_PRIVATE_KEY: ${{ secrects.SSH_PRIVATE_KEY }}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ody55eus/ana
        dockerfile: ana/alpine/Dockerfile
        tags: alpine

  build-ana-bookworm:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build the ana bookworm Docker image
      uses: docker/build-push-action@v1
      env:
        SSH_PRIVATE_KEY: ${{ secrects.SSH_PRIVATE_KEY }}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ody55eus/ana
        dockerfile: ana/bookworm/Dockerfile
        tags: bookworm
