name: Docker image

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file trajectory-recognition/Dockerfile --tag trajectory-recognition:$(date +%s)
