name: Docker image

on: [push]

jobs:

  build-trajectory:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file trajectory-recognition/Dockerfile --tag trajectory-recognition:$(date +%s)


  build-evaluate:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file evaluate/Dockerfile --tag evaluate:$(date +%s)


  push-trajectory:
    steps:
    - uses: actions/checkout@v1
    - name: Pushes Trajectory docker image
      run: docker tag trajectory-recognition:$(date +%s) ody55eus/trajectory-recognition:$(date +%s)
      run: docker push ody55eus/trajectory-recognition:$(date +%s)
  
  push-evaluate:
    steps:
    - uses: actions/checkout@v1
    - name: Pushes Evaluate docker image
      run: docker tag evaluate:$(date +%s) ody55eus/evaluate:$(date +%s)
      run: docker push ody55eus/evaluate:$(date +%s)
