name: Docker image

on: [push]

jobs:

  build-emacs-straight:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build the emacs-straight Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ody55eus/emacs-straight
        dockerfile: emacs-straight/Dockerfile
        tags: latest

  build-publish:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build the publish Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ody55eus/publish
        dockerfile: publish/Dockerfile
        tags: latest
