name: Docker image

on: [push]

jobs:

  build-trajectory:

    runs-on: ubuntu-latest

    steps:
    - name: Build the trajectory Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ody55eus/trajectory-recognition
        file: trajectory-recognition/Dockerfile
        tags: latest


  build-evaluate:

    runs-on: ubuntu-latest

    steps:
    - name: Build the evaluate Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        file: evaluate/Dockerfile
        repository: ody55eus/evaluate
        tags: latest
